<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPc6sQVg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPc6sQVg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPc6sQVg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPc6sQVg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPc6sQVg\App_KernelDevDebugContainer([
    'container.build_hash' => 'Pc6sQVg',
    'container.build_id' => '1b68246a',
    'container.build_time' => 1576687987,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPc6sQVg');
